### ISSUE TITLE
Add workaround for Celo/Gnosis issue

### ISSUE THREAD

**Issue by hiaux0** [PrimeDAO/prime-launch-dapp#768]
### Task
! There are no mocks for this yet, so please extrapolate according to your standards
- [ ] In the "Thank you" page (after seed creation), add
  - [ ] Only on Celo (ie. not on Ethereum)
  - [ ] section, that displays "data-field" for the user (https://github.com/PrimeDAO/prime-launch-dapp/blob/e6c3070d35f575ff529bb708c3d540c50ec6454e/src/services/SeedService.ts#L230)
  - [ ] have a copy button for the user
  - [ ] A word of caution, that this is a "one-time copy paste, so please make sure to store it"

### Background
- Celo Safe does not support adding Delegate via API ([notion](https://www.notion.so/primedao/Celo-Safe-Issue-outline-f59f5e150d2243eebb97ba2303417c13))
- This is a quick and "easy" workaround from the FE perspective

**Comment by testing-life** [comment]
initial visual implementation
![image](https://user-images.githubusercontent.com/85691163/188608868-1a024955-ff64-4ae1-9f1d-46304eac24f4.png)
@hiaux0 thoughts ?
